[package]
name = "ergo-lib-wasm"
version = "0.1.0"
authors = ["Denys Zadorozhnyi <denys@zadorozhnyi.com>", "ross-weir"]
edition = "2021"
description = "WASM + JS bindings for ergo-lib"
repository = "https://github.com/ergoplatform/ergo-lib-wasm"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.60"
wasm-bindgen = "0.2.63"
ergo-lib = "0.22.0"
getrandom = {version = "0.2.3", features = ["js"]}
derive_more = "0.99.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.91"
tsify = "0.4.3"
ergo-wasm-derive = { path = "../ergo-wasm-derive" }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
