[package]
name = "authenticated-avl-tree"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.83"
js-sys = "0.3.60"
scorex_crypto_avltree = "0.1.0"
derive_more = "0.99.17"
ergo-wasm-derive = { path = "../ergo-wasm-derive" }
ergo-lib-utils = { path = "../ergo-lib-utils" }
getrandom = { version = "0.2.9", features = ["js"] }
bytes = { version = "1.0.1" }


[dev-dependencies]
wasm-bindgen-test = "0.3.0"
web-sys = "0.3.63"
wasm-logger = "0.2.0"
base16 = "0.2.1"
