[package]
name = "scorex-buffer"
version = "0.0.0"
edition = "2021"

[lib]
crate_type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
sigma-ser = "0.11.0"
js-sys = "0.3.60"
ergo-lib-utils = { path = "../ergo-lib-utils" }
console_error_panic_hook = "0.1.7"
