[package]
name = "ergo-merkle-tree-wasm"
version = "0.1.0"
authors = ["ross-weir"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3.60"
wasm-bindgen = "0.2.63"
ergo-merkle-tree = "0.8.1"
getrandom = {version = "0.2.3", features = ["js"]}
derive_more = "0.99.17"
serde-wasm-bindgen = "0.4.5"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
