[package]
name = "ergo-wasm-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
wasm-bindgen = "0.2.86"
js-sys = "0.3.63"
